apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservice
  labels:
    release: microservice
spec:
  selector:
    matchLabels:
      app: microservice
  endpoints:
  - port: metrics
