apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  labels:
    app: microservice
spec:
  replicas: 4
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        #replace <foobar> with your container registry. Example: contosodemo.azurecr.io
        image: faidtsmicrosvcsspringbootregistry.azurecr.io/azure-pipelines-canary-k8s:#{Build.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8080
      imagePullSecrets:
      - name: faidtsmicrosvcsspringbootregistry.azurecr.io
