apiVersion: v1
kind: Service
metadata:
  name: microservice
  labels:
    app: microservice
spec:
  selector:
    app: microservice
  ports:
  - name: metrics
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
